[package]
name = "ipinfo"
description = "ipinfo: A Rust library for IPInfo"
version = "0.1.0"
authors = ["Amr Ali <amralicc@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/amrali/ipinfo-rs/"
readme = "README.md"
categories = ["network-programming"]
keywords = ["ip", "geolocation", "ipinfo", "ip-address"]
exclude = [".gitignore", ".travis.yml", ".cargo/config"]

[badges]
travis-ci = { repository = "amrali/ipinfo-rs", branch = "master" }
codecov = { repository = "amrali/ipinfo-rs", branch = "master", service = "github" }

[dependencies]
reqwest = "0.9"

[profile.release]
overflow-checks = true
lto = true
